server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: auth
  zipkin:
    enabled: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: mysecretpassword
  liquibase:
    change-log: classpath:liquibase/changelog/db.changelog-master.xml
    database-change-log-table: auth_databaseChangeLog
    database-change-log-lock-table: auth_databaseChangeLogLock
    parameters:
      auth.schemaName: obauth


webClient:
  loadBalanced:
    maxConnections: 100
    isKeepAlive: false
  default:
    maxConnections: 100
    isKeepAlive: false

