server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: auth
  zipkin:
    enabled: false
  r2dbc:
    url: "r2dbc:postgresql://localhost:5432/postgres?currentSchema=obauth"
    username: postgres
    password: mysecretpassword
  liquibase:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    change-log: /liquibase/changelog.xml
    url: "jdbc:postgresql://localhost:5432/postgres"
    database-change-log-table: auth_databaseChangeLog
    database-change-log-lock-table: auth_databaseChangeLogLock
    parameters:
      auth.schemaName: obauth


webClient:
  loadBalanced:
    maxConnections: 100
    isKeepAlive: false
  default:
    maxConnections: 100
    isKeepAlive: false

