spring:
  application:
    name: products
  zipkin:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: mysecretpassword

server:
  port: 8103

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


webClient:
  loadBalanced:
    acquireTimeout: 100
    maxConnections: 100
    isKeepAlive: false
  default:
    acquireTimeout: 100
    maxConnections: 100
    isKeepAlive: false

investments:
  service:
    url: http://investments
