logging:
  config: products/config/logback.groovy


server:
  port: 8101

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: products
  cloud:
    config:
      enabled: false
  zipkin:
    enabled: false

webClient:
  loadBalanced:
    acquireTimeout: 100
    maxConnections: 100
    isKeepAlive: false
  default:
    acquireTimeout: 100
    maxConnections: 100
    isKeepAlive: false