apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image }}/{{ .Values.imageTag }}"
        imagePullPolicy: {{ default ":latest" .Values.imagePullPolicy | quote }}
        env:
        - name: SERVICE_NAME
          value: {{ .Values.name }}
        - name: NAMESPACE_FULL
          value: {{ .Values.namespace.full }}
        - name: NAMESPACE_SHORT
          value: {{ .Values.namespace.short }}
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Values.spring.profiles.active }}
        - name: SPRING_CLOUD_CONFIG_URI
          value: {{ .Values.spring.cloud.config.uri }}
        - name: SPRING_CLOUD_CONFIG_LABEL
          value: {{ .Values.spring.cloud.config.label }}
        - name: SPRING_CLOUD_CONFIG_FAIL_FAST
          value: "true"
        - name: LOGGING_PATH
          value: "/var/log/{{ .Values.name }}"
        - name: JAVA_TOOL_OPTIONS
          value: -Xmx128m
        ports:
        - name: "port"
          containerPort: {{ .Values.service.port }}
        resources:
          limits:
            memory: 1G
            cpu: "5"
          requests:
            memory: 1G
            cpu: "10m"
        volumeMounts:
          - mountPath: "/var/log"
            name: log-volume
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: log-volume-gateway-0
      imagePullSecrets:
      - name: regcred