apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "port"
      port: {{ .Values.service.port }}
      targetPort: "port"
  selector:
    app: {{ .Values.name }}
