server:
  port: 8888

logging:
  config: config-server/config/logback.groovy

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

webClient:
  loadBalanced:
    maxConnections: 100
    isKeepAlive: false
  default:
    maxConnections: 100
    isKeepAlive: false

