spring:
  application:
    name: notifications
  config:
    import: "configserver:${spring.cloud.config.uri}"

logging:
  config: ${spring.cloud.config.uri}/notifications/default/${spring.cloud.config.label}/logback.groovy
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS, Europe/Moscow"
